WIP - Added ViewLayer components
UCSolarCarTeam/Epsilon-Hermes pull request #12
Opened 2017-03-19 16:04 UTC by bill-luu

Copied and pasted files from https://github.com/UCSolarCarTeam/Epsilon-Desktop-Client-Telemetry and made changes to the appropriate `.pro` files.

2017-03-19 16:06 UTC, bill-luu commented
Hey @enochtsang before you review this, I'm getting a strange `undefined reference to ViewContainer::ViewContainer()` error, which is strange and giving me aids since I'm certain that I have all the includes and `.pro`s set up right. Can you take a look and see what the issue is?

2017-03-20 03:42 UTC, enochtsang commented
The command line args should be set up in this PR. I will take a look at the problem.

2017-03-23 14:31 UTC, ExtraGravity requested changes

2017-03-23 14:31 UTC, enochtsang commented on ViewLayer/ViewContainer.h
> +enum class Mode { HERMES, TELEMETRY };
I'd prefer `HEADLESS, GUI`

2017-03-23 17:35 UTC, enochtsang commented
I'll test this when I get home, but code changes look good. You need to format the repo though.

2017-03-24 03:25 UTC, enochtsang commented
I would expect some sort of GUI to come up, even in an error state. This is not the case currently.

2017-03-24 03:35 UTC, bill-luu commented
I could add `resets` for the Business and the Communication container after the `viewContainer` one, but I would imagine that the ViewLayer will need access to those layers. Should I do something along the lines of  
`viewLayer_.reset(new ViewContainer());`
`businessContainer_.reset(new BusinessContainer());`
`viewLayer_.addBusinessContainer(*BusinessContainer)`

2017-03-30 09:43 UTC, enochtsang commented
To reiterate from our FB chat, Comm Layer should loop in error if it's headless mode, if it's headless mode it won't even try to connect without response from the GUI.

2017-04-01 21:42 UTC, bill-luu commented
Is there a better way of including `Mode.h`? I feel like this is pretty janky right now. I'm unable to forward declare it, so I'm wondering if there are alternatives to forward declaring or if I'm just doing it wrong. 

Also, I noticed that not just the comms layer needs to be changed, for instance the business layer shouldn't be forwarding stuff in `GUI` mode. I'll have to look into the extent of what needs to be changed.

2017-04-17 18:03 UTC, enochtsang commented
I agree it's weird to have Mode.h everywhere. That should probably be abstracted acutally, so for example instead of passing the Mode into ViewLayer, the ViewLayer just doens't get instantiated if the Mode is headless. Another example is UdpMessageForwarder just takes in an argument of True or False on whether to initiate a connection right away or not. So we try not to propogate the mode down, but instead of make decisions as early on as we can.

2017-05-04 05:05 UTC, enochtsang commented
New plan for desktop.

Run Hermes to convert serial to json, send to localhost. Run webserver and access webpage via localhost.

2017-05-04 05:05 UTC, closed without merging