Revision of Naming: replacing "Delta" with "Epsilon"
UCSolarCarTeam/Epsilon-Hermes pull request #14
Opened 2017-03-25 19:24 UTC by louisj381

2017-03-27 13:31 UTC, ExtraGravity requested changes

2017-03-27 13:31 UTC, enochtsang commented on .gitignore
> +SchulichEpsilonDesktopTelemetry.pro.*
This should just be `*.pro.*`

2017-03-27 13:31 UTC, enochtsang commented on SchulichEpsilonHermes/SchulichEpsilonHermes.cpp
> +#include "InfrastructureLayer/InfrastructureContainer.h"
I don't see the old files removed in this PR, they should be removed in this PR.

2017-03-27 13:39 UTC, enochtsang commented
Your build is also failing, get that patched up.

2017-04-05 02:22 UTC, bill-luu requested changes

2017-04-05 02:22 UTC, bill-luu commented on BusinessLayer/LoggerService/LoggerService.cpp.bak
> +#include <QDebug>
Please remove this file. `.bak` files come from running AStyle and are the original files before being edited. Usually these are removed in the `format.sh`, so I'm not really sure how this is here O_o

2017-04-05 02:24 UTC, bill-luu commented on BusinessLayer/LoggerService/LoggerService.cpp.bak
> +#include <QDebug>
Actually, `.orig` files are the ones that come from AStyle....this `.bak` file must have been from somewhere else then

2017-04-05 02:25 UTC, bill-luu commented
There is a Merge Conflict too, so please fix that.

2017-04-08 17:36 UTC, bill-luu commented
The `.bak` file still needs to be removed.

2017-04-10 05:08 UTC, merged