Bill/hermes qa
UCSolarCarTeam/Epsilon-Hermes pull request #33
Opened 2018-01-30 06:52 UTC by bill-luu

Fixes #32 
# Changelog

- Fixed the data lengths of the decoded message (Previously, the message length constants included the metadata, however they were being used _after_ the packet was already decoded.

- Fixed a typo in KeyMotorPopulator's expecting to receive itself in it's `connect`

- Fixed the `MessageDecodingHelpers` as outlined in #32.

Check out this amazing gif to see how hermes works now:
![hermesgood](https://user-images.githubusercontent.com/15304203/35552018-3633ac60-054f-11e8-8b81-894e442c403b.gif)

2018-01-30 21:58 UTC, ExtraGravity requested changes
Looks good! As an idea, we can't really tell right now which faults are fresh and which are not. What we can do it set the faults listed in the UI to be gray after like 20 seconds or something (bonus points if we can get them to fade out!)

2018-01-30 21:58 UTC, enochtsang commented on CommunicationLayer/MessagingFramework/MessageDefines.cpp
> +    const int BATTERY_DATA_LENGTH = 51;
This doesn't match the document. A comment is probably necessary to explain why all these are 4 shorter than our docs.

2018-01-30 21:58 UTC, enochtsang commented on CommunicationLayer/MessagingFramework/MessageDecodingHelpers.cpp
> +    unsigned short value;
These should be moved closer to where they're being used.
And I'd say there is more empty lines in these functions then are necessary.

2018-01-30 22:09 UTC, bseto commented on CommunicationLayer/MessagingFramework/MessageDecodingHelpers.cpp
> +    QDataStream dataStream(data.mid(startIndex, numberOfBytesInData(Type::UNSIGNED_INT)));
The only difference between the 3 functions really... are the type of return, and then `Type::UNSIGNED_INT` `Type::UNSIGNED_SHORT` etc

There's a couple ways you could go about getting rid of the copy pasta code :P 

Using one Template to completely replace all 3 functions (hardest part would be matching the `T` value to find out what `Type::<type>` to use)

Or probably easier: make use of a helper function that uses a Template

```
//Helper function
template <class T>
void readQDataStream(QDataStream dataStream, T &var) {
   dataStream.setByteOrder(QDataStream::LittleEndian);
   dataStream >> var;
}
// Your normal function
unsigned int MessageDecodingHelpers::getUnsignedInt(const QByteArray& data, int startIndex) {
    unsigned int value;
    QDataStream dataStream(data.mid(startIndex, numberOfBytesInData(Type::UNSIGNED_INT)));
    readQDataStream<unsigned int>(dataStream, value);
    return value;
}

float MessageDecodingHelpers::getFloat(const QByteArray& data, int startIndex) {
    float value;
    QDataStream dataStream(data.mid(startIndex, numberOfBytesInData(Type::FLOAT)));
    readQDataStream<float>(dataStream, value);
    return value;
}
```

Not sure if worth it :P, and not sure if it works 100%. But could be a good opportunity to make use of your c++ knowledge.

2018-02-03 17:36 UTC, nathanaelhuh requested changes

2018-02-03 17:36 UTC, Reddragoneer1 commented on CommunicationLayer/MessagingFramework/MessageDefines.cpp
> +    const int MOTOR_DETAILS_DATA_LENGTH = 69;
MOTOR_DETAILS_DATA_LENGTH does not match communications protocol. Not sure which one is wrong

2018-02-05 17:37 UTC, nathanaelhuh approved these changes

2018-02-05 22:03 UTC, ExtraGravity approved these changes

2018-02-07 03:08 UTC, merged