Magnus/aux bms additions
UCSolarCarTeam/Epsilon-Hermes pull request #36
Opened 2018-03-03 22:01 UTC by mglyngberg

Added 3 new values for the aux BMS:
Strobe BMS Light
Allow Charge
Contactor Error

2018-03-03 23:15 UTC, nathanaelhuh approved these changes
Looks good to me

2018-03-08 21:09 UTC, ExtraGravity requested changes
The Aux BMS is a separate system than the BMS, even though it is reliant. These changes should not be categorized under just Battery I think.

2018-03-10 17:25 UTC, bill-luu commented
Should we create a new section in the protocol for the aux battery then? Right now it's all together.

2018-03-12 06:51 UTC, enochtsang commented
Yea, I think it should be separate. Every system is it's own thing conceptually in the protocol, that's how I designed it anyways. Any new systems should follow suit.

2018-04-26 16:03 UTC, bill-luu requested changes

2018-04-26 16:03 UTC, bill-luu commented on CommunicationLayer/MessagingFramework/MessageDefines.cpp
> +    const int BATTERY_FAULTS_DATA_LENGTH = 7;
Why was this changed? I think this should still be 6

2018-04-26 16:03 UTC, bill-luu commented on DataLayer/DataLayer.pro
> +    AuxBmsData/AuxBmsData.cpp
Weird indent here

2018-04-26 16:03 UTC, bill-luu commented on CommunicationLayer/MessagingFramework/MessageDefines.h
> +        AUX_BMS = 12
Actually, let's change this to 11, it doesn't make sense to leave a gap here haha

2018-04-26 16:03 UTC, bill-luu commented on CommunicationLayer/MessagingFramework/MessageDefines.h
> +        AUX_BMS = 12
This needs to be updated on the test tool & ccs PRs as well.

2018-04-26 16:09 UTC, bill-luu requested changes

2018-04-26 16:09 UTC, bill-luu commented on BusinessLayer/JsonMessageBuilder/JsonMessageBuilder.cpp
> +            auxBmsJson[JsonFormat::PRECHARGE_STATE] = "IDLE";
These are still using the old values of precharge state. We are expecting values of OFF, COMMON_ENGAGED, CHARGE_ENGAGED, ALL_ENGAGED as according to the protocol. Sorry for not catching this sooner.

2018-04-29 01:43 UTC, bill-luu requested changes
Run format as well

2018-04-29 01:43 UTC, bill-luu commented on Tests/BusinessLayer/JsonMessageBuilder/JsonMessageBuilderTest.cpp
> +            \"PrechargeState\": \"IDLE\", \
This needs to be changed to OFF

2018-04-29 10:14 UTC, ExtraGravity approved these changes
I'm just reviewing for overall architecture, looks good. I trust @bill-luu's review on all the small stuff.

2018-04-29 21:02 UTC, bill-luu approved these changes

2018-04-29 21:02 UTC, merged