Mppt data is stored as a float instead of an int
UCSolarCarTeam/Epsilon-Hermes pull request #79
Opened 2019-09-07 21:07 UTC by mglyngberg

Fixes #78

2019-09-07 21:30 UTC, bill-luu requested changes

2019-09-07 21:30 UTC, bill-luu commented on src/DataLayer/MpptData/MpptUnit.h
> +    double getArrayVoltage() const;
Switch to float

2019-09-07 21:38 UTC, bill-luu approved these changes

2019-09-14 17:10 UTC, nathanaelhuh approved these changes

2019-09-26 00:38 UTC, merged