User/mglyngberg/sft 119
UCSolarCarTeam/Epsilon-Hermes pull request #82
Opened 2020-03-21 21:18 UTC by mglyngberg

Fixes SFT-119 Add new aux bms telemetry protocol fields to hermes

Rename Contactor Error -> HighVoltageEnableState, 
Rename HighVoltageEnable -> AllowDischarge

Add fields for AuxContactor and AuxTrip

The spreadsheet should be updated once this is merged:
https://docs.google.com/spreadsheets/d/1soVLjeD9Sl7z7Z6cYMyn1fmn-cG7tx_pfFDsvgkCqMU/edit#gid=782574835

2020-03-28 19:13 UTC, mglyngberg commented
Some of the terminology doesn't line up between the serial and internet protocol in the spreadsheet eg.  ChargeContactorError (serial) vs ContactorErrorCharge (internet). They should probably be consistent, but I'm not sure which terminology we prefer. In this pr all of the json keys match up with the serial terminology, so it is out of line with the internet protocol laid out in the spreadsheet.

2020-04-09 01:44 UTC, bill-luu commented
Oops, it should have been `ChargeContactorError`, I'll give it another pass to make sure it is consistent

2020-05-02 19:01 UTC, ThomasVy approved these changes

2020-05-09 20:27 UTC, bill-luu requested changes

2020-05-09 20:27 UTC, bill-luu commented on src/CommunicationLayer/MessagingFramework/MessageDefines.cpp
> +    const int AUX_BMS_DATA_LENGTH = 23;
Shouldn't this be 17, not 23? Given the last element at index 16 is a uchar

2020-05-09 20:27 UTC, bill-luu commented on src/DataLayer/AuxBmsData/AuxBmsData.cpp
> +    return auxMaskedBit(ORION_CAN_RECEIVED_RECENTLY_MASK);
You have `auxMaskedBit` called with `ORION_CAN_RECEIVED_RECENTLY_MASK` and `CHARGE_TRIP_DUE_TO_HIGH_CELL_VOLTAGE_MASK`, which are both `0x01`. Did you mean to create a `auxContactorMaskedBit` function too?

2020-05-22 01:00 UTC, bill-luu approved these changes

2020-05-24 20:31 UTC, bill-luu approved these changes

2020-05-31 19:14 UTC, bill-luu requested changes
`auxContactorDebug`->`auxContactorDebugInfo`, to match up with the spreadsheet <3

2020-06-06 17:46 UTC, bill-luu approved these changes

2020-06-13 21:00 UTC, merged